### ISSUE TITLE
LoadViewer not found after Package update 0.1.21 to 0.1.24 (and 0.1.37)

### ISSUE THREAD

**Issue by Hypermobile12** [simutaroman/Blazor3D#27]
Hi There,

After a while, i tried to update working Code to the latest version.
I've got an error i cannot fix:

hope you can help me out?

![image](https://github.com/HomagGroup/Blazor3D/assets/102034611/fc590842-195b-423e-9cf5-e40dac1ae6de)

**Comment by simutaroman** [comment]
It looks like no js code was added to the nuget package
I'm sorry. It's a bug. I'll fix it as soon as possible. If you need a working copy now, please update to 0.1.34

**Comment by simutaroman** [comment]
fixed in 0.1.38. try yet another time.
Probably you need to clear the cache

**Comment by Hypermobile12** [comment]
I thought it wasn't Fixed, But after multiple F5's  reload, clear cache, F12'sForced Reload.
It starts to work again :-)

<Viewer UseDefaultScene=@true></Viewer>  is Working again :-) thx

**Comment by simutaroman** [comment]
Yes, it requires clearing the cache. And this is a problem. Because the end user doesn't know this
